server:
  port: 8080

spring:
  application:
    name: CMS_TEST
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cms
      auto-index-creation: true
  datasource:
   url: jdbc:mysql://localhost:3306/cms_test?createDatabaseIfNotExist=true
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate.ddl-auto: update
   show-sql: true
   open-in-view: false
  properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL8Dialect



#logging
logging:
  file:
    path: /var/log/moglix/cms_test/
    name: /var/log/moglix/cms_test/cms_test.log
  level:
    root: info
    org:
      springframework: info
      springframework.data.mongodb.core.MongoTemplate: DEBUG
      org.springframework.data.mongodb.repository.Query: DEBUG

    com:
      zaxxer:
        hikari:
          HikariConfig: debug

upload:
  basepath: D:\upload